{
        "home": "Home",
        "phrasebook": "Frasario",
        "preferences": "Preferenze",

        "website": "Website",

        "typeSomethingHere": "Digita qualcosa qui ...",

        "clear": "Pulisci",
        "openImageFile": "Apri file immagine",
        "more": "More",
        "fullscreen": "Schermo intero",
        "exitFullscreen": "Esci da schermo intero",
        "translate": "Traduci",
        "translateFrom": "Traduci da",
        "didYouMean": "Intendevi",

        "errorOccured": "C'è stato un errore.",
        "cannotConnectToServer":"Impossibile connettersi il server.    	         	   Si prega di verificare la connessione Internet.",
        "cannotOpenTheFile": "La app non può aprire il file selezionato.",
        "cannotRecognizeImage":"La app non è in grado di riconoscere alcun testo 	   sull'immagine.",

        "listen": "Ascolta",
        "stop": "Ferma",

        "swap": "Swap",
        "copy": "Copia",
        "copied": "Copiato negli Appunti",
        "share": "Condividi",
        "addToPhrasebook": "Aggiungi a frasario",
        "removeFromPhrasebook": "Rimuovi dal frasario",

        "translatedByYandexTranslate": "Realizzato da Yandex.Translate.",
        "translatedByYandexDictionary": "Realizzato da Yandex.Dictionary.",

        "fromLanguage": "Da {1}",

        "chooseAnInputLanguage": "Traduci da",
        "chooseAnOutputLanguage": "Traduci in",

        "displayOriginalText": "Visualizza il testo originale",
        "displayTranslatedText": "Visualizza testo tradotto",
        "copyOriginalText": "Copia testo originale",
        "copyTranslatedText": "Copia testo tradotto",
        "displayTextOnly": "Visualizza solo testo",
        "phrasebookIsEmpty": "Il frasario è vuoto",

        "delete": "Cancella",
        "spaceBar": "Barra spaziatrice",
        "done": "Fatto",

        "red": "Rosso",
        "pink": "Rosa",
        "purple": "Viola",
        "deepPurple": "Viola profondo",
        "indigo": "Indaco",
        "blue": "Blu",
        "lightBlue": "Azzurro",
        "cyan": "Ciano",
        "teal": "Teal",
        "green": "Verde",
        "lightGreen": "Verde chiaro",
        "orange": "Arancione",
        "deepOrange": "Arancione profondo",
        "brown": "Marrone",
        "blueGrey": "Blu Grigio",
        "grey": "Grigio",
        "darkGrey": "Grigio Scuro",
        "black": "Nero",

        "theme": "Tema",
        "automatic": "Automatico",
        "light": "Light",
        "dark": "Scuro",

        "attachToMenubar": "Allega alla barra del menu",
        "attachToTaskbar": "Allega alla barra delle applicazioni",

        "primaryColor": "Colore primario",
        "translateWhenPressingEnter": "Traduci quando premi Invio",
        "realtime": "Traduzione in tempo reale",

        "rateMacAppStore": "Valuta Translatium sul Mac App Store",
        "rateMicrosoftStore": "Valuta la traduzione su Microsoft Store",

        "displayLanguage": "Visualizza la lingua",
        "change": "Cambia",
        "close": "Chiudi",

        "quit": "Abbandona",

        "appearance": "Aspetto",
        "restartRequired": "Riavvio richiesto",
        "advanced": "Avanzato",
        "about": "Informazioni su",

        "shortcuts": "Tasti rapidi",
        "openInputLangList": "Seleziona la lingua di input",
        "openOutputLangList": "Seleziona la lingua di output",
        "swapLanguages": "Scambia le lingue",
        "clearInput": "Cancella testo di input",
        "saveToPhrasebook": "Salva nel frasario",

        "searchLanguages": "Cerca Lingue",
        "noLanguageFound": "Nessuna Lingua Trovata",
        "searchResults": "Risultati di Ricerca",
        "recentlyUsed": "Usato di Recente",
        "allLanguages": "Tutte le Lingue",

        "remove": "Remuovi",
        "andSaveToHistory": "& salva nella cronologia",

        "save": "Salva",
        "resetToDefault": "Riportare alle condizioni prdefinite",
        "cancel": "Cancella",

        "pasteFromClipboard": "Incolla dagli Appunti",

        "popclipExtension": "Estensione PopClip",

        "support": "Supporto",

        "auto" : "Rilevamento automatico",

        "af": "Africano",
        "am": "Amarico",
        "ar": "Arabo",
        "az": "AzerO",
        "ba": "Aschiro",
        "be": "Biellorusso",
        "bg": "Bulgaro",
        "bn": "Bengalese",
        "bs": "Bosniaco",
        "ca": "Catalano",
        "ceb": "Cebuano",
        "cs": "Cecoslovacco",
        "cy": "Gallese",
        "da": "Danese",
        "de": "Tedesco",
        "el": "Greco",
        "en": "Inglese",
        "eo": "Esperanto",
        "es": "Spagnolo",
        "et": "Estone",
        "eu": "Basco",
        "fa": "Persiano",
        "fi": "Finlandese",
        "fr": "Francese",
        "ga": "Irlandese",
        "gd": "Gaelico Scozzese",
        "gl": "Galiziano",
        "gu": "Gujarati",
        "he": "Ebraico",
        "hi": "Hindi",
        "hr": "Croato",
        "ht": "Haitiano",
        "hu": "Ungherese",
        "hy": "Armeno",
        "id": "Indonesiano",
        "is": "Islandese",
        "it": "Italiano",
        "ja": "Giapponese",
        "jv": "Giavanese",
        "ka": "Georgiano",
        "kk": "Kazako",
        "km": "Khmer",
        "kn": "Kannada",
        "ko": "Coreano",
        "ky": "Kyrgyz",
        "la": "Latino",
        "lb": "Lussemburghese",
        "lo": "Lao",
        "lt": "Lituano",
        "lv": "Lettone",
        "mg": "Malgascio",
        "mhr": "Mari",
        "mi": "Maori",
        "mk": "MacedonE",
        "ml": "Malayalam",
        "mn": "Mongolo",
        "mr": "Marathi",
        "mrj": "Hill Mari",
        "ms": "Malese",
        "mt": "Maltese",
        "my": "Burmese",
        "ne": "Nepalese",
        "nl": "Olandese",
        "no": "Norvegese",
        "pa": "Punjabi",
        "pap": "Papiamento",
        "pl": "Polacco",
        "pt": "Portoghese",
        "ro": "Rumeno",
        "ru": "Russo",
        "si": "Singalese",
        "sk": "Slovacco",
        "sl": "Sloveno",
        "sq": "Albanese",
        "sr": "Serbo",
        "su": "Sudanese",
        "sv": "Svedese",
        "sw": "Swahili",
        "ta": "Tamil",
        "te": "Telugu",
        "tg": "Tajik",
        "th": "Thai",
        "tl": "Tagalog",
        "tr": "Turco",
        "tt": "Tatar",
        "udm": "Udmurt",
        "uk": "Ucraino",
        "ur": "Urdu",
        "uz": "Uzbeko",
        "vi": "Vietnamita",
        "xh": "Xhosa",
        "yi": "Yiddish",
        "zh": "Cinese"
}
