export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const UPDATE_SETTING = 'UPDATE_SETTING';

export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_OUTPUT = 'UPDATE_OUTPUT';
export const UPDATE_IME_MODE = 'UPDATE_IME_MODE';
export const TOGGLE_FULLSCREEN_INPUT_BOX = 'TOGGLE_FULLSCREEN_INPUT_BOX';

export const PLAY_TEXT_TO_SPEECH = 'PLAY_TEXT_TO_SPEECH';
export const STOP_TEXT_TO_SPEECH = 'STOP_TEXT_TO_SPEECH';

export const UPDATE_HANDWRITING_SUGGESTION_LIST = 'UPDATE_HANDWRITING_SUGGESTION_LIST';

export const UPDATE_SPEECH_STATUS = 'UPDATE_SPEECH_STATUS';

export const UPDATE_PHRASEBOOK = 'UPDATE_PHRASEBOOK';

export const UPDATE_HISTORY = 'UPDATE_HISTORY';

export const UPDATE_ALERT_MESSAGE = 'UPDATE_ALERT_MESSAGE';

export const UPDATE_OCR = 'UPDATE_OCR';

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
