export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const SET_PREFERENCE = 'SET_PREFERENCE';

export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_OUTPUT = 'UPDATE_OUTPUT';
export const TOGGLE_FULLSCREEN_INPUT_BOX = 'TOGGLE_FULLSCREEN_INPUT_BOX';

export const UPDATE_PHRASEBOOK = 'UPDATE_PHRASEBOOK';
export const UPDATE_PHRASEBOOK_QUERY = 'UPDATE_PHRASEBOOK_QUERY';

export const UPDATE_HISTORY = 'UPDATE_HISTORY';

export const UPDATE_ALERT_MESSAGE = 'UPDATE_ALERT_MESSAGE';

export const UPDATE_OCR = 'UPDATE_OCR';

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

// Language List
export const UPDATE_LANGUAGE_LIST_SEARCH = 'UPDATE_LANGUAGE_LIST_SEARCH';
export const UPDATE_LANGUAGE_LIST_MODE = 'UPDATE_LANGUAGE_LIST_MODE';

// Shortcut Dialog
export const DIALOG_SHORTCUT_CLOSE = 'DIALOG_SHORTCUT_CLOSE';
export const DIALOG_SHORTCUT_OPEN = 'DIALOG_SHORTCUT_OPEN';
export const DIALOG_SHORTCUT_SET_COMBINATOR = 'DIALOG_SHORTCUT_SET_COMBINATOR';

// General
export const UPDATE_SHOULD_USE_DARK_COLORS = 'UPDATE_SHOULD_USE_DARK_COLORS';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';
export const UPDATE_IS_MAXIMIZED = 'UPDATE_IS_MAXIMIZED';

// TTS
export const START_TEXT_TO_SPEECH = 'START_TEXT_TO_SPEECH';
export const END_TEXT_TO_SPEECH = 'END_TEXT_TO_SPEECH';

// Router
export const CHANGE_ROUTE = 'CHANGE_ROUTE';

// Dialog About
export const DIALOG_ABOUT_CLOSE = 'DIALOG_ABOUT_CLOSE';
export const DIALOG_ABOUT_OPEN = 'DIALOG_ABOUT_OPEN';

// System Preferences
export const SET_SYSTEM_PREFERENCE = 'SET_SYSTEM_PREFERENCE';

// History Page
export const UPDATE_HISTORY_PAGE = 'UPDATE_HISTORY_PAGE';
export const UPDATE_HISTORY_PAGE_QUERY = 'UPDATE_HISTORY_PAGE_QUERY';
