export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const SET_PREFERENCE = 'SET_PREFERENCE';

export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_OUTPUT = 'UPDATE_OUTPUT';
export const TOGGLE_FULLSCREEN_INPUT_BOX = 'TOGGLE_FULLSCREEN_INPUT_BOX';

export const UPDATE_PHRASEBOOK = 'UPDATE_PHRASEBOOK';

export const UPDATE_HISTORY = 'UPDATE_HISTORY';

export const UPDATE_ALERT_MESSAGE = 'UPDATE_ALERT_MESSAGE';

export const UPDATE_OCR = 'UPDATE_OCR';

export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';

export const UPDATE_LANGUAGE_LIST_SEARCH = 'UPDATE_LANGUAGE_LIST_SEARCH';

// Shortcut Dialog
export const DIALOG_SHORTCUT_CLOSE = 'DIALOG_SHORTCUT_CLOSE';
export const DIALOG_SHORTCUT_OPEN = 'DIALOG_SHORTCUT_OPEN';
export const DIALOG_SHORTCUT_SET_COMBINATOR = 'DIALOG_SHORTCUT_SET_COMBINATOR';

export const UPDATE_IS_DARK_MODE = 'UPDATE_IS_DARK_MODE';
export const UPDATE_IS_FULL_SCREEN = 'UPDATE_IS_FULL_SCREEN';

// TTS
export const START_TEXT_TO_SPEECH = 'START_TEXT_TO_SPEECH';
export const END_TEXT_TO_SPEECH = 'END_TEXT_TO_SPEECH';

// Locale
export const UPDATE_LOCALE = 'UPDATE_LOCALE';
