export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_PHRASEBOOK = 'ROUTE_PHRASEBOOK';
export const ROUTE_PREFERENCES = 'ROUTE_PREFERENCES';
export const ROUTE_LANGUAGE_LIST = 'ROUTE_LANGUAGE_LIST';
export const ROUTE_OCR = 'ROUTE_OCR';
