export const ROUTE_HOME = 'ROUTE_HOME';
export const ROUTE_PHRASEBOOK = 'ROUTE_PHRASEBOOK';
export const ROUTE_SETTINGS = 'ROUTE_SETTINGS';
export const ROUTE_LANGUAGE_LIST_INPUT = 'ROUTE_LANGUAGE_LIST_INPUT';
export const ROUTE_LANGUAGE_LIST_OUTPUT = 'ROUTE_LANGUAGE_LIST_OUTPUT';
export const ROUTE_OCR = 'ROUTE_OCR';
