export const UPDATE_SETTING = 'UPDATE_SETTING';

export const SCREEN_RESIZE = 'SCREEN_RESIZE';

export const EXPAND_INPUT = 'EXPAND_INPUT';
export const COLLAPSE_INPUT = 'COLLAPSE_INPUT';
export const TOGGLE_EXPANDED = 'TOGGLE_EXPANDED';
export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_HOME_MULTIPLE = 'UPDATE_HOME_MULTIPLE';

export const PLAY_TTS = 'PLAY_TTS';
export const STOP_TTS = 'STOP_TTS';

export const UPDATE_PHRASEBOOK = 'UPDATE_PHRASEBOOK';

export const UPDATE_HANDWRITING_SUGGESTION_LIST = 'UPDATE_HANDWRITING_SUGGESTION_LIST';

export const UPDATE_SPEECH_RECOGNITION_STATUS = 'UPDATE_SPEECH_RECOGNITION_STATUS';

export const UPDATE_OCR_MULTIPLE = 'UPDATE_OCR_MULTIPLE';
export const TOGGLE_SHOW_ORIGINAL = 'TOGGLE_SHOW_ORIGINAL';
